name: every-12-hours-cron
on:
  schedule:
    - cron: "0 1,13 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://quit-league-helper.vercel.app/api/check-user-matchhistory'
